[project]
name = "dad-music"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "millify>=0.1.1",
    "numpy>=2.0",
    "youtube-search>=2.2.0",
    "yt-dlp[default]>=2026.7.4",
]

[dependency-groups]
dev = [
    "ruff>=0.16.2",
    "taskipy>=1.14.1",
    "ty>=0.0.70",
]

[tool.taskipy.tasks]
lint = "ruff check"
post_lint = "ruff format --check"
lint_fix = "ruff check --fix"
post_lint_fix = "ruff format"
typecheck = "ty check"
